package org.reactome.web.elv.client.common.events;

/**
 * @author Antonio Fabregat <fabregat@ebi.ac.uk>
 */
public enum ELVEventType {
    ELV_READY,
    DATABASE_OBJECT_REQUIRED,
    DATABASE_OBJECT_DETAILED_VIEW_REQUIRED,

    /* CENTER PANEL EVENTS */
    CENTER_PANEL_TOOL_RESET,

    /* ANALYSIS EVENTS */
    ANALYSIS_COMPLETED,
    ANALYSIS_ERROR,
    ANALYSIS_TAB_PATHWAY_SELECTED,
    ANALYSIS_TAB_RESOURCE_SELECTED,

    /* HIERARCHY EVENTS */
    HIERARCHY_READY,
    HIERARCHY_EVENT_SELECTED,

    /* DIAGRAM EVENTS */
    DIAGRAM_ANALYSIS_ID_RESET,
    DIAGRAM_ENTITY_SELECTED,
    DIAGRAM_ENTITIES_SELECTED,
    DIAGRAM_FIGURE_SELECTED,
    DIAGRAM_ILLUSTRATION_CLOSED,
    DIAGRAM_OVERLAY_CLEARED,
    DIAGRAM_SUBPATHWAY_SELECTED,
    DIAGRAM_LOADED,

    /* PANELS */
    DETAILS_PANEL_RESIZED,
    DETAILS_PANEL_TAB_CHANGED,
    HIERARCHY_PANEL_RESIZED,

    /* TOP BAR EVENTS */
    TOPBAR_SPECIES_LIST_REQUIRED    ,
    TOPBAR_SPECIES_LOADED,
    TOPBAR_SPECIES_SELECTED,
    TOPBAR_SHOW_DETAILS_BUTTON_TOGGLED,
    TOPBAR_SHOW_HIERARCHY_BUTTON_TOGGLED,
    TOPBAR_SHOW_DIAGRAM_KEY_BUTTON_TOGGLED,
    TOPBAR_ANALYSIS_SELECTED,

    /* POPUP MANAGER EVENTS */
    DIAGRAM_KEY_OPENED,
    DIAGRAM_KEY_CLOSED,

    /* NEW PARTICIPATING MOLECULES TAB*/
    MOLECULES_ITEM_SELECTED,
    MOLECULES_DOWNLOAD_STARTED,

    /* DETAILS VIEW */
    DETAILED_VIEW_LOADED,

    /* OVERVIEW TAB */
    OVERVIEW_EVENT_SELECTED,
    OVERVIEW_ITEM_SELECTED,

    /* DATA MANAGER EVENTS*/
    DATA_MANAGER_LOAD_ERROR,
    DATA_MANAGER_OBJECT_DETAILED_VIEW_RETRIEVED,
    DATA_MANAGER_OBJECT_TUPLE_RETRIEVED,
    DATA_MANAGER_SPECIES_LIST_RETRIEVED,

    /* ORTHOLOGOUS MANAGER */
    ORTHOLOGOUS_MANAGER_STATE_SELECTED,

    /* STATE MANAGER EVENTS */
    STATE_MANAGER_ANALYSIS_TOKEN_SELECTED,
    STATE_MANAGER_ANALYSIS_TOKEN_RESET,
    STATE_MANAGER_DATABASE_OBJECTS_REQUIRED,
    STATE_MANAGER_DATABASE_OBJECTS_SELECTED,
    STATE_MANAGER_DETAILS_TAB_SELECTED,
    STATE_MANAGER_ERROR,
    STATE_MANAGER_INSTANCES_INITIAL_STATE,
    STATE_MANAGER_SPECIES_SELECTED,
    STATE_MANAGER_TARGET_REACHED,
    STATE_MANAGER_TOOL_SELECTED,
    STATE_MANAGER_TOOLS_INITIAL_STATE,
    STATE_MANAGER_WRONG_STATE,

    /* TOUR MANAGER EVENT */
    TOUR_MANAGER_TOUR_CANCELLED,
    TOUR_MANAGER_TOUR_FINISHED,
    TOUR_MANAGER_TOUR_PROGRESS,
    TOUR_MANAGER_TOUR_STARTED
}
